---
- hosts: all
  tasks:
    - name: Load Integratorr Config
      include_vars: ~/.integratorr.yml

    - name: Clone User Projects
      git: repo={{ item.url }}
           dest=~/integratorr-work/{{ item.name }}
      with_items: user_projects
