---
# This file "installs" integratorr. Assumes Ansible and other basic dependencies
# have been met.
- hosts: all
  tasks:
    - name: Symlink int.sh into the PATH
      file: path=/usr/local/bin/int state=link src={{ integratorr_home }}/int.sh mode=0755
      sudo: yes
