---
# This file "installs" integratorr. Assumes Ansible and other basic dependencies
# have been met.
- hosts: all
  tasks:
    - name: Symlink int.sh into the PATH
      template: dest=/usr/local/bin/int src={{ integratorr_home }}/int.sh mode=0755
      sudo: yes
