---
# This script is intended to be run by the Vagrant Ansible provisioner.
# When Integratorr is deployed to a non-vagrant machine, the dependencies
# in this file should be installed however the admin sees fit before
# installing Integratorr via install.yml.
- hosts: all
  tasks:
    - apt: update_cache=yes cache_valid_time=3600
      sudo: yes

    - name: Install git
      apt: pkg=git
      sudo: yes

    - name: Install python-pycurl
      apt: pkg=python-pycurl
      sudo: yes

    - name: Install python-apt
      apt: pkg=python-apt
      sudo: yes

    - name: Add Ansible repo
      apt_repository: repo=ppa:rquillo/ansible
      sudo: yes

    - name: Install Ansible
      apt: pkg=ansible
      sudo: yes
