---
- hosts: all
  tasks:
    - name: Load Integratorr Config
      include_vars: ~/.integratorr.yml
    - name: Clone User Projects
      git: repo={{ item }}
           dest=~/integratorr-work/
      with_items: user_projects
